### ISSUE TITLE
packet.py doesn't work

### ISSUE THREAD

**Issue by wangsu502** [lizrice/ebpf-beginners#3]
Hi Liz,
I got the following error, could you help to figure out what was wrong? 

root@iubuntu2004:~/ebpf-beginners# python3.9 packet.py
bpf: Attaching prog to eth0: Operation not supportedTraceback (most recent call last):
  File "/root/ebpf-beginners/packet.py", line 32, in <module>
    b.attach_xdp(dev="eth0", fn=b.load_func("hello_packet",
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 726, in attach_xdp
    raise Exception("Failed to attach BPF to device %s: %s"
Exception: Failed to attach BPF to device b'eth0': Success

**Comment by peiqiaoWang** [comment]
same problem

**Comment by ntk148v** [comment]
Hi @peiqiaoWang @wangsu502, just change [eth0](https://github.com/lizrice/ebpf-beginners/blob/main/packet.py#L32) with your actual network interface, for example: `ens3`.

**Comment by Bharat-maker** [comment]
Not working.. same Problem..
Getting below error

bpf: Attaching prog to enX0: Invalid argument
Traceback (most recent call last):
  File "//packet.py", line 32, in <module>
    b.attach_xdp(dev="enX0", fn=b.load_func("hello_packet",
  File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 940, in attach_xdp
    raise Exception("Failed to attach BPF to device %s: %s"
Exception: Failed to attach BPF to device b'enX0': Invalid argument
